README.md
=> #61 power up Readme 

packages/README.md, packages/frontend/.dockerignore, packages/frontend/.gitignore, packages/frontend/.vscode/settings.json, packages/frontend/Dockerfile-production, packages/frontend/README.md, packages/frontend/docker-compose.yaml
docker composeのバグ修正
- レビュー起動用の packages/docker-compose.yaml と開発用の packages/frontend/docker-compose.yamlに分離しました。
- node_modules と .next がコピーされて不具合を起こしていたと思われるので、Dockerから外すなど対応しました。
- READMEに起動手順を記載しました。
=> Fix Docker

.github/workflows/text2Diagram.yml
=> fix text2Diagram

packages/frontend/plop/components/component.tsx.hbs, packages/frontend/plop/components/sample.tsx.hbs, packages/frontend/plop/components/snapshot.test.tsx.hbs, packages/frontend/plop/components/story.tsx.hbs, packages/frontend/plop/plopfile.js
=> fix plop template

.github/workflows/actions.yml, packages/frontend/package.json
なぜか ci/ と書いていたようなので ci: にしました
/ はファイルパスと混同する可能性があるため避けたい.
=> ci/ を ci: にした

packages/shared/openapi/externalapi/openapi.yaml
Closes #95 
actor取得endpointのopenapi定義を追加します。
codegenでのコード自動生成は別PRで行う予定です。
=> Actor取得endpointのopenapi定義を追加

packages/frontend/package.json, packages/frontend/pnpm-lock.yaml
Closes #58
jestよりvitestの方が周辺ツールが強力っぽいのと、最新の波に乗っておくべきということで移行しました。
https://vitest.dev/guide/ui.html
=> vitestへの移行

packages/frontend/.vscode/settings.json
=> 改行コードの指定: LF

packages/shared/openapi/internalapi/openapi.yaml
なし
frontend向けにサンプルのendpointを定義していましたが、使わなさそうなので削除します。
=> 不要なsample endpointを削除

packages/backend/app/domains/actors/factory.go, packages/backend/app/domains/actors/get.go, packages/backend/app/domains/actors/ports/input_port.go
#168 
Actor取得のdomain logicを実装しました。
このdomain logicを使用するendpointの作成を優先するので、テストコードは以下のissueにて後ほど対応します。
#177
=> Actor取得のdomain logicを追加

packages/backend/.golangci.yaml, packages/backend/app/controllers/internalapi/v1/user.go, packages/backend/app/domains/types/actor_id.go, packages/backend/app/domains/types/unix_time.go
=> golangciの設定を一部修正

packages/backend/app/repositories/dao/actor_dao.go
=> Actor DAOを追加

packages/backend/app/usecases/actors/usecase.go
=> Actor取得endpointのusecase logicを追加

packages/backend/app/cmd/inits/db.go, packages/backend/app/cmd/internalapi/main.go, packages/backend/app/controllers/internalapi/v1/handler.go, packages/backend/app/controllers/internalapi/v1/user.go, packages/backend/app/domains/types/actor_id.go, packages/backend/go.mod, packages/backend/go.sum
Closes #145 
user取得endpointのcontrollerおよびmainのlogicを追加します。
=> User取得endpointのmain/controller logicを追加

packages/frontend/src/components/common/PlatCell/PlatCell.tsx
備忘録として #184 のチケットに対応する Todo コメントを記載いたしました。
=> add todo comment #184

packages/shared/openapi/internalapi/openapi.yaml, packages/shared/openapi/internalapi/parameters/plat_id.yaml, packages/shared/openapi/internalapi/paths/plat.yaml, packages/shared/openapi/internalapi/schemas/ErrorResponse.yaml, packages/shared/openapi/internalapi/schemas/Plat.yaml, packages/shared/openapi/internalapi/schemas/PlatID.yaml, packages/shared/openapi/internalapi/schemas/PlatPost.yaml
#150 #148 #153
plat取得のためのendpointをopenapiで記述しました。
platには本文とplatIDがあるものと仮定しています。画像やuser名など必要なものがあれば別PR等で書き足してください。
=> plat取得・投稿・削除のendpointをopenapiで定義

packages/shared/openapi/externalapi/openapi.yaml
=> HostMetaの定義を追加

packages/shared/openapi/internalapi/parameters/user_id.yaml, packages/shared/openapi/internalapi/schemas/UserID.yaml
none
user_id != actor_idであり、descriptionの記述が間違っていたため、これを修正します。
=> user_idに関するdescriptionの一部修正

packages/backend/README.md
Closes #48 
backendのpackage構成に関する記述をREADMEに追記します。
=> Add description about backend structure to README

packages/shared/openapi/internalapi/openapi.yaml, packages/shared/openapi/internalapi/parameters/plat_id.yaml, packages/shared/openapi/internalapi/parameters/timeline_id.yaml, packages/shared/openapi/internalapi/paths/plats.yaml, packages/shared/openapi/internalapi/paths/timelines.yaml, packages/shared/openapi/internalapi/schemas/PlatPost.yaml
Closes #243
timeline取得endpointのopenapi定義を追加します。
加えて、他のendpointについても以下の修正を加えました。
- コード生成の際にエラーが発生する箇所の修正
- 表記揺れの改善
=> timeline取得endpointのopenapi定義を追加

packages/frontend/README.md, packages/frontend/package.json, packages/frontend/pnpm-lock.yaml
テストを可視化しやすくしました
> pnpm test
を実行するとテストサーバーが立ち上がります
テストの再実行、テスト結果の確認、console.logの確認、カバレッジの確認等全てテストサーバー上で実施できます
pnpm test のコマンド自体もホットリロードなので作業中は画面操作不要です
=> vitest uiの追加

packages/backend/app/domains/types/unix_time.go, packages/backend/mock/cmd/internalapi/main.go, packages/backend/mock/controllers/internalapi/v1/handler.go
none
timeline取得endpointのmockを追加します。
mockなのでtestは書いていません。
localにて意図した挙動を取ることを確認しました。
```
% curl -i localhost:8080/internal/v1/timelines/1
HTTP/1.1 200 OK
Content-Type: application/json; charset=UTF-8
Date: Sun, 07 Jan 2024 04:04:41 GMT
Content-Length: 1167
[{"content":"plat 4","created_at":"2024-01-07T13:04:41.918174+09:00","images":["localhost:8080/internal/v1/images/1","localhost:8080/internal/v1/images/2","localhost:8080/internal/v1/images/3"],"plat_id":"0001JSM8Y9FAZD7AZPJG2SXRDY"},{"content":"plat 3","created_at":"2024-01-07T13:04:41.918174+09:00","images":["localhost:8080/internal/v1/images/1","localhost:8080/internal/v1/images/2","localhost:8080/internal/v1/images/3"],"plat_id":"0001JSM8WDJ62JFWF122Q513NB"},{"content":"plat …
```
=> timeline取得endpointのmockを追加

packages/shared/openapi/externalapi/openapi.yaml
=> Webfinger#93

packages/shared/openapi/internalapi/openapi.yaml, packages/shared/openapi/internalapi/paths/plats.yaml
Closes #152 
Closes #158
platにfavoriteを追加・削除するAPIのOpenAPI定義を書きました。
=> favorite追加、削除機能を追加

packages/backend/app/domains/plats/factory.go, packages/backend/app/domains/plats/ports/input_port.go, packages/backend/app/domains/plats/post.go
Closes #194
plat作成機能のdomain layerを実装しました。
関数名はPostPlatにしていますが、CreatePlatでもいいような気がしました。どちらがいいでしょうか？
=> plat作成のdomain layerを実装

packages/backend/app/cmd/inits/logger.go, packages/backend/app/cmd/internalapi/main.go, packages/backend/app/domains/actors/factory.go, packages/backend/app/domains/actors/get.go, packages/backend/app/logger/app.go, packages/backend/app/pkg/logger/logger.go, packages/backend/app/pkg/logger/zap.go, packages/backend/app/usecases/actors/usecase.go, packages/backend/go.mod
Closes #34 
backend packageのloggerを追加します。
loggerは以下の2つのlayerに分けられます。
- app/logger
- stlatica独自で出力するparameterをセットします（trace id, execution time etc.）
- https://github.com/stlatica/stlatica/blob/main/docs/designs/log_design.md#%E3%83%AD%E3%82%B0%E3%83%91%E3%83%A9%E3%83%A1%E3%83%BC%E3%82%BF
- app/pkg/logger
- logの出力先を抽象化します（rollbar, 標準出力 etc.）
- このpackageにはstlatica独自のドメイン知識は含まれず、他のサービスなどでも使いまわせるようになる想定です。
local環境にて意図したlogが出力されることを確認しました。
```
2024-02-04T20:46:20.023+0900    INFO    logger/app.go:27        info log
2024-02-04T20:46:20.025+0900    ERROR   logger/app.go:32        error log
github.com/stlatica/stlatica/packages/backend/app/logger.(*AppLogger).Error
/Users/xxx/src/github.com/stlatica/stlatica/packages/backend/app/logger/app.go:32 …
```
=> backend用のloggerを追加

packages/backend/Makefile
make targetを一覧で表示させるためのtagetを追加します。
以下使用例）
```
~/src/.../packages/backend add_make_list_command [!] % make list                               
make list
make install-tools
make start-local-db
make create-migration-file
make migration-up
make migration-down
make generate-code-from-db
make codegen-from-oapi
make lint
make start-local-internalapi
make start-docker-internalapi
make stop-docker-internalapi
```
=> Add list target in Makefile

packages/backend/app/repositories/dao/plat_dao.go
Closes #218
plat作成のrepository layerを実装しました。
platのCreatedAtにはtypes.UnixTime(0)を入れていますが、適切なものがあればコメントください。
=> Post plat repository/#218

packages/backend/db/migrations/20240218205040_add_timelines.sql, packages/backend/db/migrations/20240218205826_add_timeline_users.sql
Closes #314 
timelineに関連するtable schemaを追加します。
=> timelineに関連するtable schemaを追加

packages/shared/openapi/internalapi/openapi.yaml, packages/shared/openapi/internalapi/parameters/timeline_queries.yaml, packages/shared/openapi/internalapi/paths/timelines.yaml
none
query parameterを使用してtimelineを取得するendpointのopenapi定義を追加します。
=> query parameterを使用してtimelineを取得するendpointを追加

packages/backend/Makefile
Goの環境がなくてもDocker + Makeでモックサーバーを起動できるようにしました。（フロントエンドの開発用）
@cotton-alta 
コマンドの命名等確認お願いします！
=> 【backend】モックサーバー起動コマンドの追加

packages/backend/app/usecases/plats/usecase.go
Closes #198 
plat作成のusecase layerを実装しました。
=> plat作成のusecase layer実装

packages/backend/db/migrations/20231029184844_new_migration.sql
#282
論理設計に基づきactor tableのスキーマを設定しました
=> actor tableのスキーマを論理設計に基づき更新

packages/backend/app/cmd/internalapi/main.go, packages/backend/app/controllers/internalapi/v1/handler.go, packages/backend/app/controllers/internalapi/v1/plat.go, packages/backend/app/domains/plats/factory.go, packages/backend/app/domains/plats/get.go, packages/backend/app/domains/plats/post.go, packages/backend/app/domains/types/unix_time.go, packages/backend/app/repositories/dao/plat_dao.go, packages/backend/app/usecases/plats/usecase.go, packages/backend/go.mod, packages/backend/go.sum
Closes #217 
plat作成endpointのcontroller layerを実装しました。
リクエストボディのjsonをパースする必要があったため、github.com/tidwall/gjson を導入しています。
jsonをパースするライブラリとして、より良いものがあればコメントお願いします。
string → type.PlatIDやstring → types.ActorIDの変換には自信がないので、良い書き方があれば教えてください。
=> Add plat controller/#217

README.md, packages/backend/README.md
バッジたくさん追加してみました。いかがでしょうか。
https://github.com/stlatica/stlatica/tree/readme-badge
https://github.com/stlatica/stlatica/tree/readme-badge/packages/backend
=> READMEをデコった

packages/frontend/remix/package.json
=> ci実行時のlintはキャッシュ使わないよう修正

packages/frontend/docker/Dockerfile.node
=> update pnpm version

.github/workflows/actions.yml, packages/frontend/remix/pnpm-lock.yaml
pnpm v9 で lockfile の形式に変更が入ったらしいので更新
本当はlockfile削除して作り直した方がいいっぽいが、remix に typescript まわりの何かしらの変更が入っているっぽく解消法不明な型エラーがでたので一旦そのままとする
=> pnpm v9でのlockfile更新

.github/workflows/actions.yml
front/ から front/remix にコード本体を移しているので CI も修正
=> ladleビルドのカレントを修正

.github/PULL_REQUEST_TEMPLATE.md
Closes #410
pull request templateの視認性改善のため、余分な改行を削除します。
=> PR template中のコメントから余分な空行を削除

.github/workflows/actions.yml
Closes #393 
github pages へのデプロイアクションの削除です
=> remove github pages action

.github/workflows/actions.yml
=> fix ci ladle build

LICENSE
Copyright (c) 2023-2024 stlatica 
で OK かご確認ください。
=> MITライセンスファイルの追加

packages/shared/openapi/Makefile, packages/shared/openapi/internalapi/openapi.yaml, packages/shared/openapi/internalapi/parameters/timeline_limit.yaml, packages/shared/openapi/internalapi/parameters/user_pagination_id.yaml, packages/shared/openapi/internalapi/paths/follows.yaml, packages/shared/openapi/internalapi/schemas/ErrorResponse.yaml, packages/shared/openapi/internalapi/schemas/UserLightweight.yaml
#451 
フォロー系API定義4つを記述しました。
要点2つを以下にまとめています。
---
負荷軽減のため、一覧画面上では使う予定のないフォロー数のプロパティ2種を削った定義を追加して利用しました。
一方、重いならキャッシュすべきであり、キャッシュしてあるなら気軽に取得してOKなので、中途半端なデータ量のせいで扱いが複雑化するぐらいならユーザー情報をすべて含めてよい気がしてきました。
とはいえ、キャッシュに乗っていない休眠アカウントのケースでは問題を引き起こしうるので、削っておいた方が無難だろうと判断し削ったままにしてあります。
この点ご意見ありましたらコメントお願いします。
---
```
/internal/v1/users/{user_id}/followers
```
と
```
/internal/v1/users/follow/{user_id}
```
で似たエンドポイントが混在していて紛らわしいぞ（意訳）とlintに怒られたため、前者の形式に統一しました。
**そのため、スプシの定義と、今回定義したAPIで差分が発生しています。**
```diff
- /internal/v1/users/follow/{user_id}
+ /internal/v1/users/{user_id}/follow
```
しかし、これはこれで紛らわしい。
極力lint無効化はやりたくないので指示に従いましたが、こちらもご意見あればお願いします。
=> フォロー系エンドポイントの定義作成

.github/PULL_REQUEST_TEMPLATE.md
Project の付与は現在自動化されており、Project が増えない限りチェックリストに記載する必要がないためコメントアウトしました。
=> Remove "project" checklist from PR template 

.github/workflows/actions.yml
プルリクエスト作成時に、gofmtでバックエンドのGoのコードをフォーマットします。
また、そのコードをコミットします。
コードのコミットのために、stefanzweifel/git-auto-commit-actionを導入しています。
また、GitHub Actionsの権限変更が必要です。
=> ciでgofmt -wを実行し、コミットする

.github/workflows/actions.yml, packages/shared/openapi/internalapi/paths/follows.yaml, packages/shared/openapi/internalapi/schemas/ErrorResponse.yaml
エラーコードを数値始まりにしていたせいで typescript の型生成時に問題が発生したので、頭にEを付与しました。
また、bundle も実行しないと参照エラーを拾えないことが判明したのでCIにbundleコマンドも追加しました。
=> OpenAPIコード生成時に数値始まりによるエラーの修正

packages/frontend/.gitignore
=> 不要なgitkeep削除

packages/backend/db/migrations/20240324205000_add_user_auth_credentials.sql
none
user_auth_credentials tableについてmigrationを行おうとしたらエラーが出たのでschemaの修正を行います。
手元で`make migration-up`を実行し、エラーが発生しないことを確認しました。
=> user_auth_credentials tableのschemaを修正

packages/backend/db/migrations/20240721184556_add_user_relations.sql
none
follow/followerの対応関係を管理するuser_relations tableのschemaを追加します。
`make migration-up`を実行し、正常にmigrationが完了することを確認しました。
```
~/src/.../packages/backend main [!] % make migration-up
/Users/xxx/src/github.com/stlatica/stlatica/packages/backend/bin/goose -dir=./db/migrations mysql "root@tcp(localhost:4000)/stlatica" up
2024/07/21 19:21:10 OK   20240721184556_add_user_relations.sql (36.65ms)
2024/07/21 19:21:10 goose: successfully migrated database to version: 20240721184556
```
=> user_relations tableを追加

renovate.json
#504 
https://docs.renovatebot.com/key-concepts/automerge/#automerge-non-major-updates
ここの設定を記述してみました
動作未検証です.
=> renovate 自動マージの設定追加

packages/backend/app/controllers/internalapi/v1/handler.go, packages/backend/app/controllers/internalapi/v1/user.go, packages/backend/app/domains/entities/user_relations.go, packages/backend/app/domains/users/get.go, packages/backend/app/domains/users/ports/get_params.go, packages/backend/app/domains/users/ports/input_port.go, packages/backend/app/repositories/dao/user_dao.go, packages/backend/app/usecases/users/ports/get_params.go, packages/backend/app/usecases/users/usecase.go
Closes #475
follows取得endpointの実装です。
curlでリクエストを送り、意図したレスポンスが返ってくることを確認しました。
```shell
% curl -i "localhost:8080/internal/v1/users/hoge1/follows?limit=1"
HTTP/1.1 200 OK
Content-Type: application/json
Vary: Origin
Date: Sun, 04 Aug 2024 06:45:35 GMT
Content-Length: 86
[{"user_id":"hoge2","username":"user_name2","summary":"","icon":"","is_public":true}]
```
=> follows取得endpointを実装

renovate.json
=> delete renovate js-app

renovate.json
=> 暴走している renovate を停止

renovate.json
renovate リベンジ
- automerge はとりあえず外したままで、手動でも負担にならない程度の量になるように調整しました。
- 具体的には gomod と npm はまとめて発行されるようにして、また weekly で動くようにしています。
- せっかく対応したのに次々似たような内容が湧き出てくるとやる気がなくなっていくので、 rate limit は解除して一斉に全部並ぶようにしています。最初こそ大量に出てきますが、ある程度運用すれば難十件も同時に並ぶことは少ないはずです。
フォークして検証しました。こんな粒度で PR が発行されます。
https://github.com/stlatica/stlatica-renovate-test/pulls
設定ファイルがごり押しすぎるので改善したかったのですが、共通化しようとすると全然意図した挙動に持っていけなかったのでこのような方法で実現しています。（特に、playwright で npm と Dockerfile をバージョン合わせないと動作しない部分を同時に更新させるのが難しく。）
=> なんかいい感じになるように Renove の設定作成

renovate.json
自動化部分を増やしました。
warn は非推奨の属性を使っていたようなので、同様の動作が期待できるものに置き変えました。
検証リポジトリ
https://github.com/stlatica/stlatica-renovate-test/pulls
=> Renovate のwarn修正、labelとassignの自動付与

renovate.json
毎週だと頻度が高すぎて作業するたびに renovate 対応している感覚なので、1ヵ月に伸ばしてよいでしょうか
=> renovateの実行間隔を1ヵ月単位に

packages/backend/.env.local.docker
=> container内部で使用する環境変数を修正

packages/frontend/package.json, packages/frontend/pnpm-lock.yaml, packages/frontend/src/zod/Plat/PlatSchema.test.ts, packages/frontend/src/zod/Plat/PlatSchema.ts
=> Remove zod

packages/backend/go.mod, packages/backend/go.sum
以下のようなエラーが出てしまったので一旦aws-sdk-go-v2のversionを下げます
```
{
"message": "operation error S3: PutObject, resolve auth scheme: resolve endpoint: endpoint rule error, Custom endpoint `:` was not a valid URI"
}
```
=> Version down aws-sdk-go-v2

packages/backend/app/cmd/internalapi/main.go, packages/backend/app/controllers/internalapi/v1/handler.go, packages/backend/app/controllers/internalapi/v1/user.go, packages/backend/app/domains/entities/users.boil.go, packages/backend/app/domains/types/image_id.go, packages/backend/app/repositories/dao/user_dao.go, packages/backend/app/repositories/entities/users.go, packages/backend/app/usecases/users/ports/adapter.go, packages/backend/app/usecases/users/usecase.go, packages/backend/db/migrations/20231029184844_add_users.sql, packages/backend/db/sqlboiler/sqlboiler.toml, packages/backend/db/sqlboiler/templates/entities.go.tpl
Closes #530
ユーザのアイコンを取得するendpointの実装を行いました。
（指定したユーザのimage_idではなく、アイコン自体が返ります。）
`GET /internal/v1/users/{user_id}/icon`
postmanで画像が取得できることを確認しました。（ブラウザからのアクセスでも取得できることを確認済みです）
=> ユーザアイコン取得endpointの実装

packages/backend/app/controllers/internalapi/v1/handler.go, packages/backend/app/controllers/internalapi/v1/plat.go
=> timeline endpointでuser_id parameterをハンドリングできるように修正

.github/workflows/actions.yml, packages/db-manager/Makefile, packages/db-manager/src/routes/api/plat/random-create/+page.server.ts
Closes #633
SDMT のCIチェックを追加します
=> Add SDMT ci check

renovate.json
package.json のバージョン固定のため
renovate 等の更新で lockファイルしか更新されないケースがあり視認性が悪い
=> renovate.json に config:js-app を追加

.github/workflows/actions.yml
.github 配下を編集しただけだとCIが実行されず困るので対象に含めるようにします
=> .github 配下を強制CI対象に設定

.github/workflows/actions.yml
=> クローズ済みTODO削除

.github/workflows/actions.yml
Closes #361 
タイムアウト時間を設定しました
全ステップにつけるのは面倒だし抜け漏れが出やすくなるのでジョブにしました
=> github action にタイムアウト設定

packages/backend/.golangci.yaml, packages/backend/app/domains/context_test/user_id_test.go, packages/backend/app/domains/contexts/user_id.go
Closes #320
contextにuser_idを設定する処理を追加します。
テストコードを記載した上で全てのテストが通ることを確認しました。
```
/Users/xxx/.goenv/versions/1.20.6/bin/go tool test2json -t /Users/xxx/Library/Caches/JetBrains/GoLand2023.1/tmp/GoLand/___go_test_github_com_stlatica_stlatica_packages_backend_app_domains_contexts.test -test.v -test.paniconexit0
=== RUN   TestUserIDValue
=== RUN   TestUserIDValue/normal
=== RUN   TestUserIDValue/context_is_nil
=== RUN   TestUserIDValue/user_id_is_not_set
--- PASS: TestUserIDValue (0.00s)
--- PASS: TestUserIDValue/normal (0.00s)
--- PASS: TestUserIDValue/context_is_nil (0.00s)
--- PASS: TestUserIDValue/user_id_is_not_set (0.00s)
=== RUN   TestDeleteUserID
=== RUN   TestDeleteUserID/normal
--- PASS: TestDeleteUserID (0.00s)
--- PASS: TestDeleteUserID/normal (0.00s)
PASS
```
=> user_idをcontextに設定する処理を追加

packages/backend/app/domains/entities/user_auth_credentials.go, packages/backend/app/repositories/dao/user_auth_credential_dao.go, packages/backend/app/repositories/dao/user_dao.go
none
login endpointで使用するuser_auth_credential daoの追加およびuser daoの更新を行います。
=> login endpointで使用するDAOを更新

packages/backend/app/domains/plats/ports/input_port.go, packages/backend/app/domains/plats/ports/output_port.go, packages/backend/app/domains/plats/post.go
Closes #610
他に修正漏れがあればコメントお願いします。
=> platのoutput-portとinput-portを正しく振り分け直す

README.md
=> READMEにセットアップ方法とディレクトリ構造を追加

packages/backend/app/domains/auth/auth.go, packages/backend/app/domains/auth/factory.go, packages/backend/app/domains/auth/ports/input_port.go, packages/backend/app/domains/auth/ports/output_port.go, packages/backend/app/usecases/auth/ports/adapter.go, packages/backend/app/usecases/auth/usecase.go
Closes #338 
Closes #339 
auth endpointのdomain layerおよびusecase layerを追加します。
※ 認証ではpreferred_user_idとpasswordを用い、その情報を元にtokenの生成を行います
=> auth endpoint用のdomain layerおよびusecase layerを追加

packages/backend/docker/Dockerfile_air
gomod のバージョンが上がったのに対してdocker側が上がっておらず、エラーで起動出来なかったため、上げました。
=> go の docker をバージョンアップ

packages/backend/docker-compose.yaml
毎回フロントエンドのdevcontainer を vscode で開く + 別でターミナル開いて backend のコンテナ起動をやっており、手間なので always にしたいです。
=> バックエンドのコンテナに restart: always 付与

renovate.json
=> [fix] メンテ止めていいパッケージは renovate 除外

README.md
READMEにTech Blog へのリンクを追加しました（みんな書いてね）
=> README / blog へのリンク追加

packages/db-manager/README.md
昨日、使い方を聞かれたのでもっと分かりやすく書いておきました
=> [fix] SDMT のつかいかたを分かりやすく書いた
